### ISSUE TITLE
[XMonad.Util.EZConfig] Function key XF86WLAN missing

### ISSUE THREAD

**Issue by schoettl** [xmonad/xmonad-contrib#27]
The `XF86WLAN` function key missing in the supported function keys of EZConfig:
http://xmonad.org/xmonad-docs/xmonad-contrib/XMonad-Util-EZConfig.html

On my ThinkPad T450s I've got this one to enable/disable wifi.
https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_T450s#Function_Keys
Edit: There are actually one more unsupported function key:

```
$ xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'
246 XF86WLAN
198 XF86AudioMicMute
```

**Comment by vrs** [comment]
I think the place to add this would be xmonad-x11? See also: https://github.com/xmonad/X11/issues/21

**Comment by byorgey** [comment]
Well, it would need to be added in both places.

**Comment by schoettl** [comment]
So in #21 there is a script to generate this keys.

Unfortunately there is no X11 header file containing this key (on my computer):

```
$ grep XF86WLAN  /usr/include/X11/*keysym.h
```
(no output)

And there is also no file for Lenovo/IBM keysym header file :(

What do you think about placing an X11 header file `Missingkeysym.h` in the repo and use the same script as in #21 to generate the bindings?

**Comment by byorgey** [comment]
I think it is in `/usr/include/X11/XF86keysym.h` as `XF86XK_WLAN`.

**Comment by schoettl** [comment]
Oh, you're right! So once someone get the script for autogeneration to run this key should get included in EZConfig...

**Comment by pjones** [comment]
Fixed with xmonad/X11#41

**Comment by m4l352k4** [comment]
I'm sorry but maybe `xF86XK_WLAN` symbol is added to xmonad/X11 but there is still no support for it in `EZConfig` and `mkKeymap`. `<XF86WLAN>` is still not listed in [the documentation](https://hackage.haskell.org/package/xmonad-contrib-0.18.1/docs/XMonad-Util-EZConfig.html#v:mkKeymap) and it still doesn't work (at least on my setup).
